### PR TITLE
Reconfigure each time and install required extensions

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by pieper** [comment]
Looks good - thanks!

**Comment by fbudin69500** [comment]
@pieper , do you plan to release it as an extension?

**Comment by pieper** [comment]
Hi Francois - it's structured for use as an extension but the use case is
definitely for developers only, not end users so I didn't push it to the
extension catalog just yet.  If you think it's working well and should be
in the catalog then we can do that.

**Comment by fbudin69500** [comment]
I think it would work well enough if there was not a specific bug I am correcting in Slicer :). Once that problem in Slicer is corrected, there is a slight modification of the code that will need to be done [here](https://github.com/pieper/CustomSlicerGenerator/blob/master/CustomSlicerGenerator/CustomSlicerGenerator.py#L369-L385)
Basically downloadAndInstallExtension() should return a boolean to be able to handle certain problems.
Other than that, I think it could be an extension. There is one thing that will need to be changed though to package it. [This](https://github.com/pieper/CustomSlicerGenerator/blob/master/Customizer/CMakeLists.txt#L14-L19) probably needs to be removed as Customizer.py cannot be compiled since it contains some variables that need to be configured.

**Comment by pieper** [comment]
Makes sense to me.  These are the sorts of issues that I thought we should sort out on a few iterations of SlicerCMF before exposing it to everyone.  I don't know if they tried it yet, but I spoke with the SlicerRT team and I believe they were exploring it.

**Comment by fbudin69500** [comment]
The only "big" remaining issue, in my opinion, is the fact that when one has both a customized Slicer and an original version of Slicer, there is a conflict with the paths to the extensions (since the customized Slicer overwrites the paths to the extensions in some configuration file), on Windows (and linux?). It does not seem to be a problem on MacOS.

**Comment by pieper** [comment]
Hi Francois -

I would have to look again, but I thought the app name is different so the
settings are independent between original slicer and custom slicers. Maybe
we can improve this?

Thanks,
Steve

**Comment by fbudin69500** [comment]
The app name is different, but for some reason the *ini file that is created on linux and Windows is still called Slicer-XXXXX.ini . On MacOS your solution works well. We would have to investigate why on the other OSes it doesn't work.

**Comment by pieper** [comment]
I see, yes, that's an issue with the extension mechanism not picking up the
app name correctly.  I'd made a fix to Slicer's code base for the regular
settings that needs to be extended to the revision-specific settings path.

https://github.com/Slicer/Slicer/blob/1bb872d451127bfcf533345aa97410c987ac0de6/Base/QTCore/qSlicerCoreApplication.cxx#L1176

QString qSlicerCoreApplication::slicerRevisionUserSettingsFilePath()const

It needs to take into account the QCoreApplication::ApplicationName as set
by this commit:

https://github.com/Slicer/Slicer/commit/454fed0f5f2f8ea18269f2bfdfc4733326c4c6d7

From a quick look at the code it seems we just need to trace through the
logic and see why the custom application name is not being picked up when
the revision-specific settings file is probed.

**Comment by fbudin69500** [comment]
@pieper ,

I actually figured out that problem. Your code in Slicer works great. There was a small problem in the code of CustomSlicerGenerator that I have corrected in one of the commit of my latest pull-request:
https://github.com/fbudin69500/CustomSlicerGenerator/commit/370f012a5756b3647e366587b186fff9eff55bda

I have improved a few more things. Feel free to comment of the different commits of my pull-request.

**Comment by pieper** [comment]
Looks better Francois!  I didn't have time for a close review (catching up
after a few days away).  Let me know if anything else is an issue.

-Steve

**Pull request merged**
